//! The programs whose first argument is a subcommand, and which ones they
//! know: for `git stauts`, `gitpush` and `git-push`.

/// The subcommands of `program`, when its first argument is one.
pub fn subcommands_of(program: &str) -> Option<&'static [&'static str]> {
    PROGRAMS
        .iter()
        .find(|(name, _)| *name == program)
        .map(|(_, subcommands)| *subcommands)
}

/// Every program with a table, for `gitpush` and `git-push`.
pub fn programs_with_subcommands() -> impl Iterator<Item = &'static str> {
    PROGRAMS.iter().map(|(name, _)| *name)
}

/// git's long options typed with one dash by mistake: `-amend`, `-continue`.
pub const GIT_LONG_OPTIONS: &[&str] = &[
    "abort",
    "all",
    "amend",
    "autostash",
    "cached",
    "continue",
    "delete",
    "detach",
    "dry-run",
    "ff-only",
    "force",
    "force-with-lease",
    "global",
    "graph",
    "hard",
    "help",
    "interactive",
    "list",
    "local",
    "mixed",
    "no-edit",
    "no-ff",
    "no-verify",
    "oneline",
    "onto",
    "orphan",
    "patch",
    "prune",
    "quiet",
    "quit",
    "rebase",
    "set-upstream",
    "skip",
    "soft",
    "squash",
    "staged",
    "stat",
    "tags",
    "track",
    "unset",
    "verbose",
    "version",
];

const PROGRAMS: &[(&str, &[&str])] = &[
    ("git", GIT),
    ("cargo", CARGO),
    ("npm", NPM),
    ("pnpm", NPM),
    ("yarn", YARN),
    ("docker", DOCKER),
    ("podman", DOCKER),
    ("brew", BREW),
    ("go", GO),
    ("pip", PIP),
    ("pip3", PIP),
    ("kubectl", KUBECTL),
    ("gh", GH),
    ("apt", APT),
    ("apt-get", APT),
    ("dnf", DNF),
    ("yum", DNF),
    ("hg", HG),
    ("terraform", TERRAFORM),
    ("tofu", TERRAFORM),
    ("conda", CONDA),
    ("gem", GEM),
    ("composer", COMPOSER),
    ("systemctl", SYSTEMCTL),
];

const GIT: &[&str] = &[
    "add",
    "am",
    "apply",
    "archive",
    "bisect",
    "blame",
    "branch",
    "bundle",
    "checkout",
    "cherry-pick",
    "clean",
    "clone",
    "commit",
    "config",
    "describe",
    "diff",
    "difftool",
    "fetch",
    "format-patch",
    "gc",
    "grep",
    "init",
    "log",
    "merge",
    "mergetool",
    "mv",
    "notes",
    "pull",
    "push",
    "range-diff",
    "rebase",
    "reflog",
    "remote",
    "reset",
    "restore",
    "revert",
    "rm",
    "shortlog",
    "show",
    "sparse-checkout",
    "stash",
    "status",
    "submodule",
    "switch",
    "tag",
    "worktree",
];

const CARGO: &[&str] = &[
    "add",
    "bench",
    "build",
    "check",
    "clean",
    "clippy",
    "doc",
    "fetch",
    "fix",
    "fmt",
    "generate-lockfile",
    "init",
    "install",
    "locate-project",
    "login",
    "logout",
    "metadata",
    "new",
    "owner",
    "package",
    "pkgid",
    "publish",
    "remove",
    "report",
    "run",
    "rustc",
    "rustdoc",
    "search",
    "test",
    "tree",
    "uninstall",
    "update",
    "vendor",
    "verify-project",
    "version",
    "yank",
];

const NPM: &[&str] = &[
    "access",
    "adduser",
    "audit",
    "bugs",
    "cache",
    "ci",
    "completion",
    "config",
    "dedupe",
    "deprecate",
    "diff",
    "dist-tag",
    "docs",
    "doctor",
    "edit",
    "exec",
    "explain",
    "explore",
    "fund",
    "help",
    "init",
    "install",
    "install-ci-test",
    "install-test",
    "link",
    "login",
    "logout",
    "ls",
    "org",
    "outdated",
    "owner",
    "pack",
    "ping",
    "pkg",
    "prefix",
    "profile",
    "prune",
    "publish",
    "query",
    "rebuild",
    "repo",
    "restart",
    "root",
    "run",
    "run-script",
    "search",
    "set",
    "shrinkwrap",
    "star",
    "stars",
    "start",
    "stop",
    "team",
    "test",
    "token",
    "uninstall",
    "unpublish",
    "unstar",
    "update",
    "version",
    "view",
    "whoami",
];

const YARN: &[&str] = &[
    "add",
    "audit",
    "autoclean",
    "bin",
    "cache",
    "check",
    "config",
    "create",
    "dedupe",
    "generate-lock-entry",
    "global",
    "help",
    "import",
    "info",
    "init",
    "install",
    "licenses",
    "link",
    "list",
    "login",
    "logout",
    "outdated",
    "owner",
    "pack",
    "policies",
    "publish",
    "remove",
    "run",
    "tag",
    "team",
    "test",
    "unlink",
    "unplug",
    "upgrade",
    "upgrade-interactive",
    "version",
    "versions",
    "why",
    "workspace",
    "workspaces",
];

const DOCKER: &[&str] = &[
    "attach",
    "build",
    "builder",
    "buildx",
    "commit",
    "compose",
    "container",
    "context",
    "cp",
    "create",
    "diff",
    "events",
    "exec",
    "export",
    "history",
    "image",
    "images",
    "import",
    "info",
    "inspect",
    "kill",
    "load",
    "login",
    "logout",
    "logs",
    "manifest",
    "network",
    "pause",
    "plugin",
    "port",
    "ps",
    "pull",
    "push",
    "rename",
    "restart",
    "rm",
    "rmi",
    "run",
    "save",
    "search",
    "secret",
    "service",
    "stack",
    "start",
    "stats",
    "stop",
    "swarm",
    "system",
    "tag",
    "top",
    "trust",
    "unpause",
    "update",
    "version",
    "volume",
    "wait",
];

const BREW: &[&str] = &[
    "analytics",
    "autoremove",
    "bundle",
    "casks",
    "cleanup",
    "commands",
    "completions",
    "config",
    "deps",
    "desc",
    "developer",
    "doctor",
    "edit",
    "fetch",
    "formulae",
    "gist-logs",
    "home",
    "info",
    "install",
    "leaves",
    "link",
    "list",
    "livecheck",
    "log",
    "migrate",
    "missing",
    "options",
    "outdated",
    "pin",
    "postinstall",
    "readall",
    "reinstall",
    "search",
    "services",
    "shellenv",
    "tap",
    "tap-info",
    "uninstall",
    "unlink",
    "unpin",
    "untap",
    "update",
    "update-reset",
    "upgrade",
    "uses",
];

const GO: &[&str] = &[
    "bug",
    "build",
    "clean",
    "doc",
    "env",
    "fix",
    "fmt",
    "generate",
    "get",
    "install",
    "list",
    "mod",
    "run",
    "telemetry",
    "test",
    "tool",
    "version",
    "vet",
    "work",
];

const PIP: &[&str] = &[
    "cache",
    "check",
    "completion",
    "config",
    "debug",
    "download",
    "freeze",
    "hash",
    "help",
    "index",
    "inspect",
    "install",
    "list",
    "search",
    "show",
    "uninstall",
    "wheel",
];

const KUBECTL: &[&str] = &[
    "annotate",
    "api-resources",
    "api-versions",
    "apply",
    "attach",
    "auth",
    "autoscale",
    "certificate",
    "cluster-info",
    "completion",
    "config",
    "cordon",
    "cp",
    "create",
    "debug",
    "delete",
    "describe",
    "diff",
    "drain",
    "edit",
    "events",
    "exec",
    "explain",
    "expose",
    "get",
    "kustomize",
    "label",
    "logs",
    "options",
    "patch",
    "plugin",
    "port-forward",
    "proxy",
    "replace",
    "rollout",
    "run",
    "scale",
    "set",
    "taint",
    "top",
    "uncordon",
    "version",
    "wait",
];

const GH: &[&str] = &[
    "alias",
    "api",
    "attestation",
    "auth",
    "browse",
    "cache",
    "codespace",
    "completion",
    "config",
    "extension",
    "gist",
    "gpg-key",
    "issue",
    "label",
    "org",
    "pr",
    "project",
    "release",
    "repo",
    "ruleset",
    "run",
    "search",
    "secret",
    "ssh-key",
    "status",
    "variable",
    "workflow",
];

const APT: &[&str] = &[
    "autoclean",
    "autopurge",
    "autoremove",
    "build-dep",
    "changelog",
    "clean",
    "depends",
    "dist-upgrade",
    "download",
    "edit-sources",
    "full-upgrade",
    "install",
    "list",
    "policy",
    "purge",
    "rdepends",
    "reinstall",
    "remove",
    "satisfy",
    "search",
    "show",
    "source",
    "update",
    "upgrade",
];

const DNF: &[&str] = &[
    "autoremove",
    "check",
    "check-update",
    "clean",
    "deplist",
    "distro-sync",
    "downgrade",
    "group",
    "help",
    "history",
    "info",
    "install",
    "list",
    "makecache",
    "mark",
    "module",
    "provides",
    "reinstall",
    "remove",
    "repolist",
    "repoquery",
    "repository-packages",
    "search",
    "shell",
    "swap",
    "update",
    "updateinfo",
    "upgrade",
    "upgrade-minimal",
];

const HG: &[&str] = &[
    "add",
    "addremove",
    "annotate",
    "archive",
    "backout",
    "bisect",
    "bookmarks",
    "branch",
    "branches",
    "bundle",
    "cat",
    "clone",
    "commit",
    "config",
    "copy",
    "diff",
    "export",
    "files",
    "forget",
    "graft",
    "grep",
    "heads",
    "help",
    "identify",
    "import",
    "incoming",
    "init",
    "log",
    "manifest",
    "merge",
    "outgoing",
    "paths",
    "phase",
    "pull",
    "push",
    "recover",
    "remove",
    "rename",
    "resolve",
    "revert",
    "rollback",
    "root",
    "serve",
    "shelve",
    "status",
    "summary",
    "tag",
    "tags",
    "unbundle",
    "unshelve",
    "update",
    "verify",
    "version",
];

const TERRAFORM: &[&str] = &[
    "apply",
    "console",
    "destroy",
    "fmt",
    "force-unlock",
    "get",
    "graph",
    "import",
    "init",
    "login",
    "logout",
    "metadata",
    "modules",
    "output",
    "plan",
    "providers",
    "refresh",
    "show",
    "state",
    "taint",
    "test",
    "untaint",
    "validate",
    "version",
    "workspace",
];

const CONDA: &[&str] = &[
    "activate",
    "build",
    "clean",
    "compare",
    "config",
    "create",
    "deactivate",
    "doctor",
    "env",
    "export",
    "info",
    "init",
    "install",
    "list",
    "notices",
    "package",
    "remove",
    "rename",
    "repoquery",
    "run",
    "search",
    "uninstall",
    "update",
    "upgrade",
];

const GEM: &[&str] = &[
    "build",
    "cert",
    "check",
    "cleanup",
    "contents",
    "dependency",
    "environment",
    "exec",
    "fetch",
    "generate_index",
    "help",
    "info",
    "install",
    "list",
    "lock",
    "mirror",
    "open",
    "outdated",
    "owner",
    "pristine",
    "push",
    "query",
    "rdoc",
    "rebuild",
    "search",
    "server",
    "signin",
    "signout",
    "sources",
    "specification",
    "stale",
    "uninstall",
    "unpack",
    "update",
    "which",
    "yank",
];

const COMPOSER: &[&str] = &[
    "about",
    "archive",
    "audit",
    "browse",
    "bump",
    "check-platform-reqs",
    "clear-cache",
    "completion",
    "config",
    "create-project",
    "depends",
    "diagnose",
    "dump-autoload",
    "exec",
    "fund",
    "global",
    "help",
    "home",
    "init",
    "install",
    "licenses",
    "list",
    "outdated",
    "prohibits",
    "reinstall",
    "remove",
    "repository",
    "require",
    "run-script",
    "search",
    "self-update",
    "show",
    "status",
    "suggests",
    "update",
    "validate",
    "why",
    "why-not",
];

const SYSTEMCTL: &[&str] = &[
    "cat",
    "daemon-reexec",
    "daemon-reload",
    "default",
    "disable",
    "edit",
    "emergency",
    "enable",
    "get-default",
    "halt",
    "help",
    "hibernate",
    "is-active",
    "is-enabled",
    "is-failed",
    "is-system-running",
    "isolate",
    "kill",
    "link",
    "list-dependencies",
    "list-jobs",
    "list-sockets",
    "list-timers",
    "list-unit-files",
    "list-units",
    "mask",
    "poweroff",
    "preset",
    "reboot",
    "reenable",
    "reload",
    "reload-or-restart",
    "rescue",
    "reset-failed",
    "restart",
    "revert",
    "set-default",
    "set-property",
    "show",
    "start",
    "status",
    "stop",
    "suspend",
    "try-reload-or-restart",
    "try-restart",
    "unmask",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_program_with_a_table_is_known_under_each_of_its_names() {
        assert!(subcommands_of("git").unwrap().contains(&"status"));
        assert!(subcommands_of("pip3").unwrap().contains(&"install"));
        assert!(subcommands_of("apt-get").unwrap().contains(&"install"));
        assert_eq!(subcommands_of("ls"), None);
    }

    #[test]
    fn every_table_is_sorted_so_a_missing_entry_is_easy_to_spot() {
        for name in programs_with_subcommands() {
            let table = subcommands_of(name).unwrap();
            assert!(
                table.windows(2).all(|w| w[0] < w[1]),
                "{name} is not sorted"
            );
        }
        assert!(GIT_LONG_OPTIONS.windows(2).all(|w| w[0] < w[1]));
    }
}
